### Real-time Audio Processing Request
POST http://localhost:3000/prompt/live
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="life.wav"
Content-Type: audio/wav

< ./api/life.wav

###

### Create Podcast Request
POST http://localhost:3000/podcasts
Content-Type: application/json

{
  "topic": "family",
  "duration": 10
}

###

### Real-time Audio Processing Request
POST http://localhost:3000/prompt
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="life.wav"
Content-Type: audio/wav

< ./api/life.wav

